pipeline:
  build:
    image: node:boron
    commands:
      - npm install
      - npm run build
    when:
      branch: master
      event: push

  publish:
    image: plugins/docker
    registry: docker.soapbubble.online:5000
    username: drone
    password: cobBomGopabyocVi
    repo: soapbubble/online
    tag: latest
    when:
      branch: master
      event: push
